apiVersion: v1
kind: ConfigMap
metadata:
  name: sayo
  namespace: sayooo
data:
  server.properties: |
    server-port=25565
    motd=A Minecraft Server on k8s
    max-players=20
    online-mode=false
