apiVersion: apps/v1
kind: Deployment
metadata:
  name: sayo
  namespace: sayooo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sayo
  template:
    metadata:
      labels:
        app: sayo
    spec:
      containers:
        - name: paper
          image: ghcr.io/xata/Sayoowo/msud-paper-gitops-lab/:latest
          ports:
            - containerPort: 25565
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: config
              mountPath: /server/server.properties
              subPath: server.properties
            - name: world
              mountPath: /server/world
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: example-paper-config
        - name: world
          persistentVolumeClaim:
            claimName: example-paper-world
