apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: sayo 
  namespace: sayooo
spec:
  gatewayClassName: envoy-gateway
  listeners:
    - name: minecraft
      protocol: TCP
      port: 31500
