apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: sayo
  namespace: sayo
spec:
  parentRefs:
    - name: example-paper-gateway
  rules:
    - backendRefs:
        - name: sayo
          port: 55555
