apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: sayo
  namespace: sayooo
spec:
  parentRefs:
    - name: sayo
  rules:
    - backendRefs:
        - name: sayo
          port: 25565
