apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-paper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/example/Sayoowo/msud-paper-gitops-lab.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: sayooo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
